### ISSUE TITLE
Header: remove max content width

### ISSUE THREAD

**Issue by mattsharkey** [web-illinois/toolkit#3] opened 2021-04-27 14:58 UTC
The width of the header content is currently capped. Per the the new designs, it should always be the width of the page (minus margins/padding).

**Comment by bryanjonker-illinois** [comment] 2021-05-18 16:23
Possible duplicate of #27

**Comment by melissawaller78** [comment] 2021-05-20 16:44
dup.

**Closed** 2021-06-02 21:19 UTC
Labels: enhancement
