### ISSUE TITLE
footer spacing between lists in safari

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#99] opened 2021-06-03 21:35 UTC
Here is Chrome (correct spacing):
![Screen Shot 2021-06-03 at 4 34 26 PM](https://user-images.githubusercontent.com/54747669/120715022-9e47c780-c489-11eb-961c-af23a4082188.png)

Here is Safari:
The spacing between lists disappears....
![Screen Shot 2021-06-03 at 3 18 17 PM](https://user-images.githubusercontent.com/54747669/120714925-79ebeb00-c489-11eb-98a1-6cf6a6137f0f.png)

**Comment by mwllr** [comment] 2021-06-03 21:35
here is the toolkit in safari...
![Screen Shot 2021-06-03 at 4 35 31 PM](https://user-images.githubusercontent.com/54747669/120715102-be778680-c489-11eb-92c9-af7a5e7c8bf9.png)

**Comment by mattsharkey** [comment] 2021-06-11 18:06
Duplicate of #113

**Closed by mattsharkey** 2021-06-11 18:06 UTC
