### ISSUE TITLE
Nav Bar Active State

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#116] opened 2021-06-11 18:17 UTC
Do any of the tests let me see if I am in an active section? 
https://cdn.brand.illinois.edu/toolkit/2.0/examples/pages/aces-research-safety/index.html
the Research tab in nav bar should be white background with active state.

So, either I need a new test page, and/or it may not be working???

**Comment by mwllr** [comment] 2021-06-11 18:59
zeplin: https://zpl.io/Vq3ROAJ

**Comment by mwllr** [comment] 2021-06-18 18:24
great ..... where can I see it?

**Comment by mattsharkey** [comment] 2021-06-18 19:34
https://cdn.brand.illinois.edu/toolkit/dev/examples/pages/aces-research-safety/index.html

**Comment by mattsharkey** [comment] 2021-06-24 14:46
Duplicate of #93

**Closed by mattsharkey** 2021-06-24 14:46 UTC
